ultimatemember/ultimatemember

- core/um-short-functions.php
This removes the trailing slashes in requests when printing strings
> Remove slashes in single and double quotes

- assets/js/um-functions.js
- core/um-access.php
- core/um-actions-access.php
- core/um-actions-form.php
- core/um-actions-wpadmin.php
- core/um-fields.php
- core/um-filters-fields.php
- core/um-members.php
- Fixed conditional form fields
- Issue was in the field validation. It keeps the target field to trigger required field even the parent field is not selected or equivalent to selected value.
-  Remove duplicate user IDs
- Here's a temporary fix for duplicate profiles in Directory.
> Fixed conditional form fields & Remove duplicate user IDs in directory

- admin/core/um-admin-actions.php
Changes text from `This is applicable only if you allow logged-in users to view the content.` to `This is applicable only if you restrict the content to logged-in users.`
> Phrasing of admin message about roles.

- core/um-actions-members.php
- core/um-filters-members.php
- templates/profile.php
- um-config.php
1. Sorting: when using a custom sort criteria such as "role", within each role the members should be sorted by display name.
2. Add CSS class for user role to member profile for further styling.
3. Add CSS class for user role to member div's in in members directory for further styling.
4. Add link to cover picture in the members directory for easier click.
5. Cover picture also in format 1.6:1 needed. 
Please check what you can merge. Thanks!
> plugin adjustments

- core/um-builtin.php
- core/um-members.php
Allows adding	**Ultimate Member - User Tags** `user_tags` fields as `select` search filters.
> Allows setting user tags fields as search filters

- core/um-shortcodes.php
- index.php
- um-init.php
adding filter hook to emoji base uri.
people of some countries ( such as China ) can NOT use s.w.org, I think there should be a filter hook.
> adding filter hook to emoji base uri

- assets/js/um-crop.js
Adding a checking  condition in um-crop.js
> Cropper js update

- admin/core/um-admin-dashboard.php
Please check and add this change
> um-admin-dashboard warning correction

- assets/js/um-scripts.js
For tickets:
https://secure.helpscout.net/conversation/175507169/5098/?folderId=646527
> Fix datepicker for ios and safari

- core/um-actions-register.php
- core/um-actions-user.php
For the ticket(s):
https://secure.helpscout.net/conversation/176435734/5179/?folderId=707112
> Fix adding of members in wp-admin

- core/um-actions-wpadmin.php
Add support for server query string data after user login
> Add support for server query string data after user login

- core/um-actions-wpadmin.php
Update the code to support query string redirect
> Update server query string redirect code

- core/um-short-functions.php
For:
[Ticket 1](https://secure.helpscout.net/conversation/175143588/5064/)
> Accept period in profile url

- core/um-query.php
> Fix for Bug in Multisite Webseites -> Edit -> Users #194

- core/um-actions-password.php
- core/um-form.php
Ultimate Member is not showing translated spam bot messages because
,'ultimatemember'
is missing.
> Fix translation of spam bot messages

- admin/core/um-admin-actions.php
- admin/core/um-admin-dragdrop.php
- admin/core/um-admin-enqueue.php
- admin/core/um-admin-filters-fields.php
- core/um-actions-access.php
- core/um-api.php
- core/um-user.php
Added H2 for UltimateMember section to Add/Edit User Form
> Nikita Sinelnikov

- core/um-members.php
> fixed search by role

- core/lib/upload/um-file-upload.php
Fixing bug which require missing wp-load.php
See ultimatemember#7
> Fix error missing wp-load.php

- includes/admin/assets/js/um-admin-modal.js
- includes/core/class-fields.php
remove conditional logic if there aren't any fields in forms
remove conditions for field from other forms
> remove value field if empty/not empty

- README.md
current link is broken so I fixed it
> Update README.md to fix broken docs link

- includes/core/class-fields.php
[https://secure.helpscout.net/conversation/992775826/34616?folderId=1041461](url)
> Add aria-label tag in Field icon

- assets/js/um-scripts.js
- includes/admin/core/class-admin-enqueue.php
- includes/admin/core/class-admin-metabox.php
- includes/admin/core/list-tables/roles-list-table.php
- includes/admin/templates/role/role-edit.php
- includes/core/class-builtin.php
- includes/core/class-fields.php
- includes/core/class-roles-capabilities.php
- includes/core/class-user.php
- includes/core/um-actions-form.php
- includes/core/um-actions-profile.php
- includes/core/um-actions-register.php
- uninstall.php
Added default array() for get_option.
> - fixed PHP notices

- includes/admin/core/class-admin-builder.php
- added a tooltip with meta key name for fields in a form settings
> Field metakey tooltip (github issue #710)

- includes/admin/core/class-admin-metabox.php
- includes/admin/templates/access/restrict_content.php
- add the administrator user role to a restriction setting (github issue #692)
> administrator user role to restriction 

- includes/core/um-actions-register.php
- fixed not-unique user emails/username on the registration without these fields;
> Registration without  email or username

- includes/core/um-actions-register.php
- fixed the issue with creating the users based on first+last name with not ASCII symbols.
> Sanitize the user_login created from first_name and last_name

- includes/core/class-fonticons.php
Fix for the method that gets a list of icons
> Empty icons are shown in the popup "Choose from... available icons"

- includes/core/class-member-directory-meta.php
- includes/core/class-member-directory.php
Sort by distance if member search returns an empty result
> Sort by distance

- includes/core/class-member-directory.php
- fix min and max values in a slider range (issue #738)
> Min and max values in a slider range

- includes/core/class-uploader.php
Fix stream_photo resize and compress feature.
> An image resize and compress may not work.

- includes/admin/core/class-admin-navmenu.php
- added an option "visible to Administrators only" in a menu an item setting (issue #766)
> Visible a menu item to Administrators only (issue #766)

- includes/um-short-functions.php
Fix: The field is visible for the profile owner if the field privacy option is "Only visible to profile owner and specific roles".
> Field privacy option "Only visible to profile owner and specific roles"

- includes/admin/core/packages/2.1.17-alpha/functions.php
- includes/admin/core/packages/2.1.17-alpha/hooks.php
- includes/admin/core/packages/2.1.17-alpha/init.php
> Profile tabs slugs upgrade

- includes/core/class-profile.php
https://secure.helpscout.net/conversation/1461558618/48705?folderId=736350
> Fixed getting active tab

- includes/admin/core/class-admin-settings.php
- includes/core/class-member-directory-meta.php
- includes/core/class-member-directory.php
- added hooks for change a wp_um_metadata table
- added hooks for user_location fields (hooks for comparison in text fields)
Pull request for user locations here - https://github.com/ultimatemember/user-locations/pull/5
> Changes for user locations filters

- includes/core/class-fields.php
Fixed: default value with comma for checkbox
> Checkbox title with commas creating issue with default option

- includes/admin/assets/js/um-admin-field.js
- includes/core/class-fields.php
- fixed permanently deleting form's field (issue #786)
> Permanently deleting form's field (issue #786)

- includes/core/class-roles-capabilities.php
- includes/core/um-actions-profile.php
- includes/um-short-functions.php
- readme.txt
- fixed editing private profiles;
> Private profiles editing

- includes/admin/core/class-admin-settings.php
- includes/core/um-actions-profile.php
- setting label changed;
- added filter hook 'um_change_usermeta_for_update' for extending $to_update usermeta array after all profile fields validations;
> Few enhancements for better integration

- includes/core/class-access.php
- exclude posts from a query for restricted posts (https://wordpress.org/support/topic/hide-from-queries-behavior/)
> Exclude posts from a query (wordpress.org support)

- includes/core/class-access.php
- exclude restricted posts from a next/prev navigation (issue #859)
- exclude comments from restricted posts
- exclude restricted posts from a recent post widget
> Restrict content exclude (issue #859)

- includes/core/class-access.php
- exclude restricted post's comments from a comments feed
> Comments feed

- includes/core/class-fields.php
Fix placeholder for the “Confirm password” field.
Image - The confirm password field placeholder in the registration form.
> User defined label text for the “Confirm password” field

- includes/admin/class-admin-functions.php
- fixed is_um_screen() function for new a widgets admin area
> fixed is_um_screen() function

- includes/core/class-fields.php
Keep description formatting in a view mode.
> Description formatting

- includes/core/class-access.php
- fixed visibility of custom link in a nav menu
> Custom link in a nav menu

- includes/core/class-form.php
- includes/core/um-actions-login.php
> - fixed #840;

- includes/admin/templates/role/role-edit.php
The role ID will be like "custom_role_123" if there are non-latin symbols in the title.
> -fixed role ID regexp

- includes/um-short-functions.php
- check variable as array (issue #913)
> Fix/um_user_submitted_registration_formatted (issue #913)

- assets/js/um-members.js
- includes/admin/assets/js/um-admin-forms.js
- includes/core/class-member-directory.php
- fixed range slider in member directory setting (issue #912)
- fixed wrong values in slider range
> Fix/member directory slider (issue #912)

- includes/core/um-actions-account.php
Update user's display_name and full_name according to the setting _"User Display Name"_ on Account update.
> Update Display name in Account update

- includes/core/um-actions-profile.php
Fixed the property twitter:site in the profile Twitter card.
> Wrong header meta for the Twitter Card

- uninstall.php
- excluded core pages from uninstalling (issue #940)
> Core pages uninstall (issue #940)

- includes/core/class-member-directory.php
- fixed range filter label (issue #924)
> Range filter label (issue #924)

- includes/core/um-filters-profile.php
Issue - Wrong canonical link
Fixed - No canonical link if not needed
Fixed - Correct canonical link if needed
> Canonical link in translated profile

- includes/core/class-builtin.php
- fixed the LinkedIn field URL (issue #933)
> LinkedIn field

- includes/core/class-builtin.php
- includes/core/um-actions-form.php
- includes/core/um-filters-fields.php
- fixed the skype field for the new skype id (issue #928 )
- added Viber, WhatsApp and Telegram fields (issue #926 )
> New user fields and skype fix (issue #926, #928)

- includes/core/class-form.php
Reverts ultimatemember/ultimatemember#902
> Revert "Add Billing/Shipping State filter to the member directory"

- includes/core/class-builtin.php
- includes/core/class-validation.php
- includes/core/um-actions-form.php
- added a discord field (issue #926)
> Discord field (issue #926)

- includes/core/class-fields.php
- Delete Member Directory displaying fields, filters, sorting (issue #801)
> Delete Member Directory displaying fields, filters, sorting

- includes/admin/core/class-admin-notices.php
- includes/admin/core/class-admin-settings.php
- added a notice after saving on the settings pages
> Add notice to the settings page

- includes/admin/core/class-admin-metabox.php
- includes/core/class-fields.php
- fixed editing upload fields (issue #958)
> Editing upload fields (issue #958)

- includes/core/um-actions-form.php
- fix uppercase usernames and emails from blacklists
> fix usernames and emails blacklists

- uninstall.php
- fixed removing UM custom capabilities from global $wp_roles;
- fixed removing UM custom roles from user roles after uninstall;
> Fixed Uninstalling process

- includes/core/class-user.php
- delete um_member_directory_data meta on user delete (issue #1015)
> Delete the user meta

- modules/online/assets/js/admin/blocks.js
- modules/online/includes/class-admin.php
> Online block

- modules/member-directory/assets/js/blocks/blocks-shortcode.js
- transfer blocks settings to the sidebar
> Change blocks settings

- includes/core/class-member-directory-meta.php
- includes/core/class-member-directory.php
- fixed ability for getting hidden user details
> Member Directory security vulnerability

- includes/admin/class-site-health.php
- modules/member-directory/includes/admin/class-site-health.php
- fix site health info if there is no data
> - fix site health info if no data

- modules/member-directory/includes/admin/class-site-health.php
- modules/online/includes/admin/class-site-health.php
- add a hook for member directory extend
> Extend member directory site health

- modules/forumwp/includes/admin/class-site-health.php
- modules/jobboardwp/includes/admin/class-site-health.php
- modules/member-directory/includes/admin/class-site-health.php
- added hooks for extending UM pro modules site health
> Extend site health

- includes/core/class-builtin.php
- includes/core/class-fields.php
- includes/core/um-filters-fields.php
- change type for phones fields (issue #988)
> Phone fields (issue #988)

- includes/core/class-password.php
- includes/core/class-user.php
- includes/core/um-actions-account.php
- templates/password-change.php
- templates/password-reset.php
Replaced from ID to the user_login
> - fixed issue with visible ID in password reset link and form

- includes/core/class-member-directory.php
> - fixed text filter label on the member directory;

- modules/recaptcha/includes/admin/class-site-health.php
- change recaptcha site health
> Site health recapthca

- includes/admin/core/class-admin-upgrade.php
> Add validation for upgrade package

- templates/members.php
Sanitize the parameter before printing into the HTML attribute.
> Sanitize View Type variable

- README.md
- includes/admin/core/class-admin-upgrade.php
- readme.txt
- ultimate-member.php
> Version 2.5.3

- includes/core/class-fields.php
- add a hook for a date field (issue https://github.com/ultimatemember/ultimatemember/issues/1096)
> Hook a for a date field

- includes/core/class-builtin.php
- includes/core/um-actions-form.php
- includes/core/um-filters-fields.php
- add TikTok, Reddit and Twitch
> New social networks

- includes/core/class-access.php
- change esc_url to esc_url_raw in the Class Access
> esc_url_raw class access

- includes/core/class-fields.php
- add the user_registered field to a restricted array of fields (issue #1154)
> Exclude registered date field from editable fields

- includes/class-init.php
Use language selected in the "Language" setting on _wp-admin > Users > Profile_ in the Ultimate Member admin dashboard.
> User language in dashboard

- includes/core/class-form.php
Fixed PHP Notice
**Notice details**
`Notice: Undefined index: options in /www/wp-content/plugins/ultimate-member/includes/core/class-form.php on line 861`
> Notice: Undefined index: options

- includes/core/um-actions-profile.php
Added hook `um_profile_dynamic_meta_image_size`
This hook can change the profile SEO image size. The default value is `190`.
Added hook `um_profile_dynamic_meta_image_type`
This hook can change the profile SEO image type: `cover_photo` or `profile_photo`. The default value is `profile_photo`.
Previously we used the 190px profile photo thumbnail, but this may be too small for preview in social networks like LinkedIn, see https://www.linkedin.com/help/linkedin/answer/a521928/make-your-website-shareable-on-linkedin?lang=en
> Change the profile SEO image

- README.md
- includes/admin/core/class-admin-columns.php
- includes/admin/core/class-admin-settings.php
- includes/admin/core/class-admin-users.php
- includes/admin/core/packages/2.6.0/functions.php
- includes/admin/core/packages/2.6.0/hooks.php
- includes/admin/core/packages/2.6.0/init.php
- includes/admin/templates/role/profile.php
- includes/class-dependencies.php
- includes/class-init.php
- includes/core/class-account.php
- includes/core/class-builtin.php
- includes/core/class-fields.php
- includes/core/class-form.php
- includes/core/class-member-directory.php
- includes/core/class-password.php
- includes/core/class-roles-capabilities.php
- includes/core/class-user.php
- includes/core/um-actions-form.php
- includes/core/um-actions-login.php
- includes/core/um-actions-profile.php
- includes/core/um-actions-register.php
- includes/core/um-filters-fields.php
- readme.txt
- templates/members.php
- ultimate-member.php
> 2.6.0 version

- includes/admin/core/class-admin-settings.php
- fix template versioning paths for extensions
> Template versioning paths

- includes/admin/class-admin.php
- includes/admin/core/class-admin-columns.php
- added wpnonce argument for the duplicate form link
> Fixed form duplicate

- includes/admin/core/class-admin-forms.php
This PR has additional attributes for the `info_text` field type in UM settings. This allows me to add style and class attributes to the info_text content.
> Add style and class attributes to info_text field type in settings

- includes/admin/core/class-admin-notices.php
> Template versioning notice

- includes/core/class-fields.php
- fix profile ID for not logged-in users when there is a register form in a widget or a block area.
> Fix profile id for not logged-in users

- includes/admin/core/class-admin-settings.php
- add missing email to the install info (issue #1163)
> Email install info

- includes/um-short-functions.php
- added the lazy load attribute to cover and profile photos
> Lazy load images

- includes/um-short-functions.php
Reverts ultimatemember/ultimatemember#1029
> Revert "Lazy load images"

- includes/admin/core/class-admin-enqueue.php
- includes/core/class-blocks.php
- change the 'block_type_metadata_settings' hook's priority
- add additional checking for restricted_blocks
> ACF and UM blocks conflict

- includes/admin/core/list-tables/roles-list-table.php
- includes/admin/templates/role/role-edit.php
- add new hooks for private content
> Hooks for private content

- .github/workflows/build-docs.yml
- includes/core/class-account.php
- includes/core/class-external-integrations.php
- includes/core/class-permalinks.php
- fixed the WPML profile URL issue
- added hook `um_permalinks_profile_url`
> WPML: Profile links are incorrect

- includes/core/um-actions-profile.php
- add a hook for nav links attributes
> Nav link attributes

- includes/core/class-builtin.php
- includes/core/class-fields.php
- includes/core/class-form.php
- includes/core/um-actions-form.php
- includes/core/um-filters-fields.php
- add a Spotify field (issue #830)
> Spotify field

- includes/admin/assets/js/um-admin-field.js
- includes/admin/core/class-admin-builder.php
- includes/admin/core/class-admin-dragdrop.php
- includes/admin/core/class-admin-metabox.php
- includes/class-init.php
- includes/core/class-builtin.php
- includes/core/class-password.php
- includes/core/class-query.php
- added hookdoc for `um_admin_builder_skip_field_validation` hook;
- updated hookdoc for `um_admin_field_update_error_handling` hook;
- fixed deprecated PHP notice for $set_field_type variable;
- fixed deprecated PHP notice for $change_password variable;
- changed htmlspecialchars to esc_attr() for form builder modal;
> Remove extract() wp-admin

- includes/admin/core/class-admin-settings.php
- change str_contains  to strpos (issue #1224)
> Template override str_contains

- includes/admin/core/class-admin-settings.php
- templates/account.php
- templates/gdpr-register.php
- templates/login.php
- templates/logout.php
- templates/members.php
- templates/message.php
- templates/password-change.php
- templates/password-reset.php
- templates/profile.php
- templates/register.php
- fix override templates (issue #1214)
- change template comments
> Override templates

- includes/admin/core/class-admin-settings.php
- fix custom emails data (issue #1213)
> Custom emails data in Install info

- README.md
- includes/admin/assets/js/um-admin-field.js
- includes/admin/core/class-admin-builder.php
- includes/admin/core/class-admin-dragdrop.php
- includes/admin/core/class-admin-metabox.php
- includes/admin/core/class-admin-settings.php
- includes/class-init.php
- includes/core/class-builtin.php
- includes/core/class-form.php
- includes/core/class-password.php
- includes/core/class-query.php
- includes/core/class-user.php
- readme.txt
- templates/account.php
- templates/gdpr-register.php
- templates/login.php
- templates/logout.php
- templates/members.php
- templates/message.php
- templates/password-change.php
- templates/password-reset.php
- templates/profile.php
- templates/register.php
- ultimate-member.php
> Version 2.6.4

- README.md
- includes/admin/core/class-admin-builder.php
- includes/class-init.php
- includes/core/class-access.php
- includes/core/class-fields.php
- includes/core/um-actions-form.php
- includes/core/um-actions-profile.php
- includes/core/um-filters-fields.php
- readme.txt
- ultimate-member.php
> Version 2.6.6

- includes/core/class-fields.php
- allowed types files (issue #1231 )
> allowed types files

- includes/core/class-fields.php
> Fix disabled_weekdays

- README.md
- includes/admin/class-admin.php
- includes/core/class-fields.php
- includes/core/class-form.php
- includes/core/class-gdpr.php
- includes/core/class-login.php
- includes/core/class-member-directory.php
- includes/core/class-register.php
- includes/core/class-user.php
- includes/core/class-validation.php
- includes/core/um-actions-account.php
- includes/core/um-actions-form.php
- includes/core/um-actions-login.php
- includes/core/um-actions-profile.php
- includes/core/um-actions-register.php
- includes/core/um-filters-fields.php
- includes/core/um-filters-login.php
- readme.txt
- ultimate-member.php
> Version 2.6.7

- includes/um-short-functions.php
- add a hook for user photos ext (https://github.com/ultimatemember/user-photos/issues/2)
> Hook for um_edit_profile_url()

- includes/core/class-fields.php
- add wp_kses for fields error
> Error field wp_kses

- includes/admin/assets/css/um-admin-settings.css
- includes/core/class-account.php
- includes/core/class-blocks.php
- includes/core/class-shortcodes.php
- fix showing blocks on the User page
- fix showing blocks on the Account page
> Account and User page blocks

- includes/admin/core/class-admin-gdpr.php
- includes/admin/core/class-admin-menu.php
- includes/admin/core/class-admin-metabox.php
- includes/admin/core/class-admin-notices.php
- includes/admin/core/class-admin-settings.php
- includes/admin/core/class-admin-upgrade.php
- includes/admin/core/list-tables/emails-list-table.php
- includes/admin/core/packages/2.0-beta1/functions.php
- includes/admin/core/packages/2.1.3-beta3/functions.php
- includes/admin/core/packages/2.3.0/functions.php
- includes/admin/templates/dashboard/cache.php
- includes/admin/templates/dashboard/purge.php
- includes/admin/templates/gdpr.php
- includes/admin/templates/modal/forms/fonticons.php
- includes/class-dependencies.php
- includes/class-extensions.php
- includes/core/class-date-time.php
- includes/core/class-fields.php
- includes/core/class-member-directory.php
- includes/core/class-password.php
- includes/core/class-uploader.php
- includes/core/um-actions-form.php
- includes/core/um-actions-profile.php
- includes/core/um-filters-fields.php
- includes/um-short-functions.php
- templates/members.php
- templates/profile/comments-single.php
- templates/profile/posts-single.php
- add translators to text stings
> Translators

- includes/admin/class-secure.php
- includes/core/class-login.php
- includes/core/class-logout.php
- includes/core/class-register.php
- includes/core/um-actions-login.php
- includes/core/um-actions-register.php
- includes/um-short-functions.php
- extend allowed hosts for the UM
- add um_safe_redirect function
> UM safe redirect

- includes/core/um-actions-account.php
- fix um_safe_redirect for deleting user
> Delete user redirect

- includes/core/um-actions-form.php
- fix counting words in a textarea field (issue #1234)
> Textarea count words

- includes/core/class-mail.php
- fix mail_from and mail_from_addr in mail settings (issue #1280)
> Empty mail from

- includes/admin/core/class-admin-settings.php
- includes/class-config.php
- includes/core/class-permalinks.php
- includes/core/class-rewrite.php
- includes/core/class-user.php
- includes/core/um-filters-user.php
It looks like Upwork user link:
You make the user profile link safe and don't tell the attackers about the user ID or user_login.
> Hash slug for user Profile link

- includes/admin/core/class-admin-builder.php
- includes/core/class-builtin.php
- add the ID to the blacklist of meta key (issue #1301)
> Fields key blacklist

- includes/um-short-functions.php
- add the ability to add shorts (issue #1307)
> Youtube shorts

- includes/core/um-filters-fields.php
- fix soundcloud field in the member directory
> Soundcloud field

- includes/core/class-builtin.php
- includes/core/class-fields.php
- includes/core/class-form.php
- includes/core/um-filters-fields.php
- add oEmbed field (issue #1310)
> oEmbed field

- includes/admin/core/class-admin-site-health.php
- includes/class-init.php
> Site health

- includes/admin/class-site-health.php
> Directory sitehealth

- includes/core/class-mail.php
- change hooks comments and fix functions name in comments (issue #1317)
> Hooks comments

- includes/admin/class-site-health.php
- add the delete comments option to the site health
> Delete comments site health

- includes/core/class-builtin.php
- includes/core/um-actions-form.php
- add a YouTube URL validation for video and shorts (issue #1325)
> Youtube URL validation

- assets/css/um-crop.css
- assets/js/um-crop.js
- assets/js/um-functions.js
- assets/js/um-modal.js
- update cropper.js
- fix the mobile devices issue - there was the wrong cropping on mobile devices (issue #1220)
> New cropper.js

- includes/admin/core/class-admin-metabox.php
- hide validation on login forms for usernames (issue #1222)
> Login validation

- includes/admin/core/class-admin-builder.php
- fixed a new line in the content block field (issue #737)
> Content block field new line

- includes/core/class-form.php
- fix special characters in social URLs (issue #1349)
> Social URL characters

- includes/core/um-actions-form.php
Fixed the Required condition validation for the Number field.
> Required condition not working for the Number field

- includes/core/class-access.php
Implement safeguards against clickjacking attacks to protect user interactions and sensitive information.
Related task: [Security report 4](https://www.notion.so/ultimate-member-roadmaps/Security-report-4-71415784cc5142f5999d19a0c9ac325a)
> Security report 4

- includes/core/um-filters-navmenu.php
- fixed conditional menu handlers for MegaMenu themes (#1334);
> MegaMenu and conditional handlers

- includes/core/class-access.php
> Update hook docs in access.php class

- includes/admin/core/class-admin-navmenu.php
- add hooks for extended nav menu (for this PR https://github.com/ultimatemember/verified-users/pull/10)
> Nav menu extend

- includes/core/um-filters-fields.php
- fixed display fields with quotes in "extra user information section" (issue ##1421)
> - fixed stripslashes in tagline

- templates/profile/posts-single.php
> Changed posts-single.php template

- includes/core/class-mail.php
- fix email background color from grey to white (issue #1405)
> Email background

- includes/class-config.php
- includes/core/class-mail.php
- includes/core/class-password.php
- includes/core/class-permalinks.php
- includes/core/class-user.php
- includes/core/um-actions-core.php
- includes/core/um-actions-register.php
- templates/email/welcome_email.php
- templates/password-change.php
- change placeholders for set password
> Add set password URL if user is registered without password

- templates/email/notification_deletion.php
- templates/email/notification_new_user.php
- templates/email/notification_review.php
- delete wrong span tags in emails
> Emails wrong tags

- includes/core/um-actions-form.php
- fix registration with the unique value for fields (issue #1418)
- some wpcs
> Registration with unique value

- includes/admin/core/class-admin-metabox.php
- fixed Notice: Undefined index: metakey in .../plugins/ultimate-member/includes/admin/core/class-admin-metabox.php on line 1497 (issue #1411)
> Login field validate

- assets/js/um-functions.js
- fix height modal responsive (issue #1429)
> Fix modal responsive

- includes/core/um-actions-form.php
- add English letters validation (issue #1417)
> English letters validation

- includes/admin/core/class-admin-theme-updater.php
- fix theme update message with custom UM templates (issue #1444)
> Theme update log

- assets/css/um-styles.css
- fix search icon CSS (issue #1431)
> Search icon CSS

- includes/core/um-actions-form.php
- added alpha_numeric validation (issue #1458)
> alpha_numeric validation to fields

- includes/core/class-member-directory-meta.php
- includes/core/um-actions-profile.php
> Member Directory custom usermeta table queries

- includes/core/class-fields.php
- fixed PHP notice on validation
> Wrong Validation PHP notice

- includes/core/class-uploader.php
- fixed integration with getting webp files for cover and profile photos
> Conflict with WebP Uploads

- includes/core/class-user.php
Seconds to Days number as expected from option name.
> Activation link time 

- includes/core/class-member-directory.php
- fixed no-escaped member card data;
> Fixed CVE-2024-2123

- assets/css/admin/common.css
- assets/css/admin/common.sass
- fix UM dashboard CSS (issue #1478)
> UM dashboard CSS

- includes/core/class-member-directory-meta.php
- includes/core/class-member-directory.php
- add a hook for the select filter relation
> Select filter relation hook

- assets/js/admin/forms.js
- remove media URL in user role settings if there is no default media (issue #1493)
> Clear media

- includes/core/um-actions-account.php
- Disable account update email if reset password email was sending (issue #1476)
> Disable duplicate emails

- includes/core/class-password.php
- fix space in username after reset password with SMTP (issue #1460)
> Reset password smtp

- includes/core/class-modal.php
- fix includes modal templates (issue #1485)
> Includes modal templates

- includes/um-short-functions.php
- YouTube Video Validation Error on Empty Unrequired Text Box (issue #1502)
> Youtube validation

- includes/core/class-member-directory-meta.php
- includes/core/class-member-directory.php
- add a single time filter for admin filters
> Single time filter

- includes/admin/core/class-admin-settings.php
- includes/common/class-cpt.php
- assign a new default form after deleting the old one (issue #1498)
> Assign default forms

- includes/core/class-member-directory-meta.php
- add a hook for member directory custom meta table (https://github.com/ultimatemember/mycred/issues/15)
> Hook for meta directory (myCred fix)

- includes/core/class-member-directory.php
- fix sort by the last login for default usermeta table
> Sort by last login

- includes/core/um-filters-fields.php
- fix rating fields in viewing profile (issue #1513)
> Rating field

- includes/core/um-actions-form.php
- fix checking for unique_email validation (issue #1518)
> Fix unique_email validation 

- includes/admin/class-secure.php
- query improvement for count users
> Count users secure settings

- includes/class-functions.php
- includes/core/class-shortcodes.php
- includes/um-short-functions.php
- templates/account.php
- templates/gdpr-register.php
- templates/login-to-view.php
- templates/login.php
- templates/logout.php
- templates/members-grid.php
- templates/members-header.php
- templates/members-list.php
- templates/members-pagination.php
- templates/members.php
- templates/message.php
- templates/modal/upload-single.php
- templates/modal/view-photo.php
- templates/password-change.php
- templates/password-reset.php
- templates/profile.php
- templates/profile/comments-single.php
- templates/profile/comments.php
- templates/profile/posts-single.php
- templates/profile/posts.php
- templates/register.php
- templates/restricted-blog.php
- templates/restricted-taxonomy.php
- templates/searchform.php
- fixed CVE ID: CVE-2024-8519
- WPCS;
> Fixed vulnerability in [um_loggedin] shortcode

- includes/core/um-actions-profile.php
- change the Schema for a person (issue #1367)
> Person schema

- changelog.txt
- includes/admin/core/class-admin-settings.php
- includes/core/class-user.php
- readme.txt
* manually reviewed https://github.com/ultimatemember/ultimatemember/tree/fix/um_member_directory_data;
> Fixes PHP error when meta `um_member_directory_data` has a wrong format

- assets/js/v3/common-frontend.js
- assets/js/v3/directory.js
- includes/core/class-fields.php
- includes/core/class-form.php
- includes/frontend/class-directory.php
- fix profile and directory callback choices for choices js
> Callback choices

- includes/admin/core/class-admin-builder.php
- includes/core/class-fields.php
Fix is created from commit 945b79a97940406b40a5996f9aa2159bd11e29ab
> Fixes issues when the custom fields meta has a wrong format

- includes/core/class-form.php
Make it impossible to create a user without a role even with an incorrect "Registration Default Role" setting.
> Fixes validation of the form slug

- includes/class-init.php
* fix based on commit 7b44add0d7b183fd8f0ddf314e023e1cc035afa2
> Fixes allowed query variables

- includes/core/class-roles-capabilities.php
* fixed `um_current_user_can()`;
> Version 2.9.1 hotifx

- .distignore
- changelog.txt
- includes/admin/templates/extensions.php
- includes/class-init.php
- readme.txt
* updated methods for properly searchable code;
> Version 2.9.2 enhancements

- includes/um-short-functions.php
- added hooks for submitted registration data
> Submitted registration data

- includes/frontend/class-directory.php
> show_filter

- includes/core/class-member-directory.php
- includes/core/um-actions-form.php
* fixed security issue CVE ID: CVE-2025-0308
* fixed security issue CVE ID: CVE-2025-0318
> Fixes security vulnerabilities

- includes/admin/core/class-admin-metabox.php
- includes/common/class-fields.php
- filter for _parent_dropdown_relationship
- extend class for form rows
> Woocommerce hooks

- includes/admin/core/class-admin-gdpr.php
- includes/admin/core/class-admin-metabox.php
- includes/admin/core/packages/2.0-beta1/user_roles.php
- includes/admin/core/packages/2.1.0-beta1/member-directory.php
- includes/admin/core/packages/2.1.0-beta1/metadata.php
- includes/admin/core/packages/2.1.3-beta3/functions.php
- includes/admin/core/packages/2.8.0/functions.php
- includes/core/class-access.php
- includes/core/class-member-directory-meta.php
- includes/core/class-member-directory.php
- includes/core/class-query.php
- includes/core/class-uploader.php
- includes/core/class-user-posts.php
- includes/core/rest/class-api-v1.php
- includes/core/rest/class-api-v2.php
- includes/um-deprecated-functions.php
- readme.txt
- ultimate-member.php
- uninstall.php
* fixed CVE-2024-12276;
* reviewed using $wpdb and WPCS;
* set minimum required version to 6.2 due to using %i for $wpdb->prepare;
> Fixes CVE-2024-12276

- templates/gdpr-register.php
Fixed the "Privacy Policy" field in the registration form. Forms and other disallowed HTML are stripped out from the "Privacy Policy" field content.
> Fix the "Privacy Policy" field in the registration form (CU-86cxva4f0)

- includes/core/um-actions-account.php
Fixed the "Erase of your data" tool's layout.
Screenshot:
> The "Erase of your data" layout (CU-86cxneg3d)

- includes/admin/core/class-admin-settings.php
- includes/core/class-member-directory.php
- ultimate-member.php
Update for CVE ID: CVE-2025-0308 and previous issues related to the injections to the member directory search.
> Security patch related to the member directory search

- includes/action-scheduler/class-init.php
- includes/admin/core/class-admin-settings.php
- includes/class-config.php
- includes/common/actions/class-emails.php
Updated the Action Scheduler implementation to improve flexibility and clarity. Replaced the 'enable_action_scheduler' option with 'enable_as_email_sending' for better specificity. Introduced hook-based checks to selectively enable email scheduling, ensuring compatibility and optimized performance.
> Refactor Action Scheduler for not only email handling.

- includes/action-scheduler/class-init.php
- includes/admin/class-site-health.php
- includes/core/class-password.php
- includes/core/class-user.php
Ensure proper handling of user data in password reset functions by adding checks and updating parameter handling. Introduce a new filter to extend site health information and include a setting for enabling email sending via Action Scheduler. Improve code clarity with updated comments and function annotations.
> Fixes reset password email for different cases

- includes/common/actions/class-emails.php
- includes/common/class-users.php
- includes/core/class-mail.php
- includes/core/class-password.php
- includes/core/class-permalinks.php
- includes/core/class-profile.php
- includes/core/class-user.php
- includes/core/um-actions-login.php
- includes/core/um-actions-register.php
- includes/um-short-functions.php
Streamline placeholder handling for emails by introducing universal patterns and replacements, and update email dispatch functions for efficiency. Deprecated various redundant user and password-related methods, consolidating logic into common utility classes for better maintainability.
> Refactor email placeholders and deprecate obsolete methods

- includes/admin/core/packages/2.0-beta1/um-cpt.php
- fix fatal error 2.0-beta1 package update (issue #1724)
> Fix package update

- includes/core/class-fields.php
- includes/core/class-files.php
- allow uploading WEBP images (issue #1747)
I think we need to allow WEBP by default, because a lot of images are already in this format
> Alllow WEBP images
