core/um-permalinks.php
This prevents an error (leaking path information on poorly configured servers) if a user supplies an array as `hash` parameter.
```
test.org/?act=activate_via_email&hash[]=hash&user_id=1
```
```
Warning: strlen() expects parameter 1 to be string, array given in /var/www/wp-content/plugins/ultimate-member/core/um-permalinks.php on line 75
```
=> Make sure the hash parameter is a string

templates/members-grid.php
This fixes a persistent Cross-Site Scripting vulnerability in the Member Directory. Malicious users could update their first and/or last name in their settings to include Javascript. This Javascript would be executed on the Member Directory page because the user's display is used in a `title` attribute without escaping double quotes (`"`). 
How to reproduce:
1. As a regular user, set your first name to `name" onmouseover=alert(document.cookie)`.
2. Navigate to the member directory (as a guest or any user).
3. Mouse-over the member photo of the user with the Javascript payload. 
4. An alert box will now pop up.
This issue is fixed by using the Wordpress function `esc_attr`. Documentation is available [here](http://codex.wordpress.org/Function_Reference/esc_attr).
----------------------
=> Escape display name in title attributes

core/um-actions-account.php
.uimob300-hide (instead of .uimob340-hide) applied to element meant the "display:none" styling did not get applied on mobile screens.
=> Correct mobile class on account delete tab heading

admin/core/um-admin-roles.php
Hi,
There is a little bug inside `remove_row_actions` function : when Ajax, $current_screen is not defined. So we can use the `$post` variable to determine if we are on the good post_type
=> Fixes notice when we use WP List Table quick edit

core/um-permalinks.php
`$user_login` is not defined, should be `$user->user_login`, and `wp_login` action should pass two params, the `$user->user_login` and `$user` object just like core, otherwise will trigger fatal error for any custom filters on `wp_login` expecting the two params to be passed
Fixes #274
=> Email Activation $user_login undefined, and wp_login action should pass 2 params

includes/core/class-fields.php, includes/core/class-profile.php
The enhancement for displaying Distance field hooked by User Location extension.
The distance field hasn't metakey, so we need to display it by the hook.
=> Fixed displaying by the hook issues with fields without metakeys

includes/admin/core/class-admin-settings.php, includes/admin/templates/role/profile.php, includes/core/class-builtin.php, includes/core/class-user.php, includes/core/um-actions-profile.php, includes/core/um-filters-account.php
New user role setting "Avoid indexing profile by search engines" is added. This setting sets the default value for the account setting "Avoid indexing my profile by search engines".
**Proposition 1**
I think it would be better to remove the account setting "Avoid indexing my profile by search engines". Users can avoid indexing by making their profiles private. Users may be confused by seeing a lot of similar settings.
**Proposition 2**
I think it would be better to change the logic to opposite - disable indexing by default and change the user role setting "Avoid indexing profile by search engines" to the "Allow indexing profile by search engines".
=> Indexing of Profiles

includes/core/class-member-directory.php
The slider range may display a NaN if the minimum value is a string. The minimum and the maximum values should be a number.
The issue was found in the ticket #46540. It appears if the value of the field type Number is an empty string. The issue can’t be reproduced now, but may be inherited from older versions. 
This branch solves the issue.
The example:
=> Fix NaN in the slider range.

includes/core/um-actions-core.php, includes/core/um-filters-user.php
This change allows users who have the capability '**edit_users**' to approve a user or change a user status.
**Note:** The 'list_users' capability allows users to view a list of users in the admin area. We have to use a stricter capability 'edit_users' for actions that change user's status.
=> Allow non-admin users to approve another users in the backend

includes/core/class-password.php
Sends the "Password Changed Email" when the password is changed via password reset page.
=> Missing Password Changed confirmation email notification after reseting password via password reset page.

assets/js/um-conditional.js, assets/js/um-functions.js, assets/js/um-jquery-form.js, assets/js/um-members.js, assets/js/um-profile.js, assets/js/um-scripts.js, includes/admin/assets/js/um-admin-dragdrop.js, includes/admin/assets/js/um-admin-field.js, includes/admin/assets/js/um-admin-form.js, includes/admin/assets/js/um-admin-forms.js, includes/admin/assets/js/um-admin-role-wrapper.js, includes/admin/assets/js/um-admin-scripts.js, includes/admin/assets/js/um-admin-settings.js, includes/core/class-user.php
jQuery.fn.change() event shorthand is deprecated
jQuery.fn.click() event shorthand is deprecated
jQuery.fn.focus() event shorthand is deprecated
jQuery.fn.keypress() event shorthand is deprecated
jQuery.fn.removeAttr no longer sets boolean properties: disabled
jQuery.fn.submit() event shorthand is deprecated
jQuery.isArray is deprecated; use Array.isArray
=> jQuery 3 compatibility (for WordPress 5.7 and higher)

includes/admin/assets/css/um-admin-global.css, includes/admin/assets/js/um-admin-blocks-shortcode.js, includes/admin/assets/js/um-admin-blocks.js
Fixed: Conditional settings "Who can access this content?", "What roles can access this content?", "Restriction Action" are hidden if the parent setting "Restrict access?" is turned off.
Image 1 - The setting "Restrict access?" is turned off.
Image 2 - The setting "Restrict access?" is turned on.
=> UM access Controls

includes/core/class-access.php
Fixed: Restricted Content message does not replace content in the site header and footer.
=> Restricted content message is showing twice and removing header

includes/core/class-access.php
Fix: Don't replace content in the Avada header.
=> Content restriction may replace header in Avada theme

includes/admin/core/class-admin-metabox.php, includes/core/class-builtin.php, includes/core/class-fields.php
Added: The field setting "Confirm password field label".
Image - The confirm password field label in the registration form.
=> User defined label text for the “Confirm password” field

includes/core/class-form.php
Don't use the function esc_url_raw to sanitize social fields. Social strings entered by users may not be URL, it may be their usernames. 
Example: If user enter {username} into the field "Twitter" it should be converted to https://twitter.com/{username}
This fix did it.
=> Social links on update profile

includes/admin/core/list-tables/roles-list-table.php
The plugin can't delete user roles that contain Asian symbols. Error message "The link you followed has expired." appears.
We have to urlencode the "id" parameter to solve this issue. We also have to use the function _sanitize_title_ instead of the function _sanitize_key_, because the function _sanitize_key_ removes the symbol "%".
Example:
=> Fix user role delete action

includes/core/um-filters-fields.php
Soundcloud allows for a track url to be used in the player instead of the track id. This patch allows either the track id or the track url to be passed to render the iframe for soundcloud.
Recreated for latest version of ultimatemember (originally submitted Dec 13, 2019)
=> Allow soundcloud URLs to be passed in addition to track ids

includes/core/um-actions-account.php
The field Username (user_login) in Account must be not editable. This field is used only for view. This field should not be used to get the current user. So, we don't need to validate this field.
=> Make Username not editable in Account

includes/core/um-actions-account.php
Export text shows to the Delete request text
=> Fix text in export and delete requests in Account > Privacy tab

includes/core/class-form.php
Support options with keys in member directory.
These changes are needed to add member directory filters `WC Billing state` and `WC Shipping state`
This pull request is related to the pull request in the extension [WooCommerce](https://github.com/ultimatemember/woocommerce).
See https://github.com/ultimatemember/woocommerce/pull/10
=> Add Billing/Shipping State filter to the member directory

includes/class-config.php
For new user admin notification email description the word approved creates confusion, this should be changed to created
https://secure.helpscout.net/conversation/1779797627/58148/
=> Change the word approved to created

includes/admin/core/class-admin-enqueue.php
Fixed error that appears on the printing of cash receipts with the plugin _Point of Sale for WooCommerce_
**Error Details**
An error of type E_ERROR was caused in line 660 of the file /home/thecoinhunter/public_html/wp-content/plugins/ultimate-member/includes/admin/core/class-admin-enqueue.php. Error message: Uncaught Error: Call to a member function is_block_editor() on null in /home/thecoinhunter/public_html/wp-content/plugins/ultimate-member/includes/admin/core/class-admin-enqueue.php:660
=> Fix $current_screen

includes/core/class-uploader.php
The GLOB_BRACE flag is not available on some non GNU systems, like Solaris or Alpine Linux. We should not use it without verification. In this case it is not needed.
**Error details**
Fatal error: Uncaught Error: Undefined constant "um\core\GLOB_BRACE" in /var/www/wp-content/plugins/ultimate-member/includes/core/class-uploader.php:1364
=> Fix for the glob function fatal error

assets/css/um-styles.css
This fix solves problems with fields that use the select2 library for RTL (right-to-left) languages.
Fields "Dropdown" and "Multi-select" may work wrong with RTL (right-to-left) languages, like Hebrew:
- The button "Remove all items" is wrongly placed in "Dropdown" fields.
- The button "Remove all items" is full-width in "Multi-select" fields and overlaps items (options).
- "Multi-select" fields have unneeded big padding right. 
**Screenshots:**
Image - Current styles
Image - Fixed RTL styles
=> Fix select2 styles for RTL languages

includes/core/class-fields.php
Fix fatal error on unset.
**Error details:**
PHP Fatal error: Uncaught Error: Cannot unset string offsets in D:\web\um\wp-content\plugins\ultimate-member\includes\core\class-fields.php:311
=> Fix fatal error on unset

assets/css/um-styles.css
The Ultimate Member styles for the select2 dropdown influences dropdowns on non-UM pages, for example the country dropdown on the WooCommerce checkout page.
Changes in this branch solve a style conflict.
**Screenshots**
Wrong dropdown styling on the WooCommerce checkout page
Fixed styling
=> Fix select2 style conflict

includes/core/class-form.php
Added data type check for "url" field when sanitise input. The field data must be an array. Otherwise, a fatal error occurs.
=> Fix error in url field

includes/core/um-actions-form.php
Fix PHP Warning that may appear if the registration form is submitted with the empty "Password" field.
Warning example:
```
[09-Jan-2023 11:58:46 UTC] PHP Warning: strpos(): Empty needle in /public_html/um.loc/wp-content/plugins/ultimate-member/includes/core/um-actions-form.php on line 624
[09-Jan-2023 11:58:46 UTC] PHP Warning: strpos(): Empty needle in /public_html/um.loc/wp-content/plugins/ultimate-member/includes/core/um-actions-form.php on line 628
```
=> Fix php warning if empty password

includes/core/class-builtin.php
Fixed colors for social links in the profile header: TikTok, Twitch, Reddit.
**Screenshots:**
Image 1 - Current view.
Image 2 - Fixed view.
=> social links colors

includes/admin/core/class-admin-settings.php
The plugin copies data from the default database tables `{$table_prefix}users` and `{$table_prefix}usermeta` to the custom database table `{$table_prefix}um_metadata` when admin turn on the **Enable custom table for usermeta** setting and run the upgrade process. See https://docs.ultimatemember.com/article/1541-meta-table-for-member-directories
But the update process does not work if the database table `{$table_prefix}um_metadata` does not exist. I propose to check whether the table exists and create a table if it does not exist before writing data into this table.
=> Create custom table for usermeta

includes/core/class-account.php, includes/core/class-password.php
The plugin can not change the password with quotes properly. This happens because WordPress adds slashes before quotes in input data. 
The plugin uses the recommended function `wp_unslash` to remove slashes from input data on registration and login, but does not do this on the Change Password.
I propose to use the `wp_unslash` function to remove slashes from input data on the Change Password.
=> Password with quotes

includes/admin/templates/role/profile.php, includes/core/class-user.php
Fixed role setting "Avoid indexing profile by search engines".
This setting has three options: "Default", "No", "Yes". The core version 2.5.4 displays and uses the "No" option wrong.
=> Avoid indexing profile by search engines

includes/core/class-fields.php
The Date Picker field does not support all date formats. For example the "Ymd" date format (like 20230308) works wrong. This may cause conflicts with third-party plugins (like ACF) that save dates in formats that Date Picker field doesn't support.
I propose to normalize a format of the Date Picker field before displaying it.
=> Date Picker field value format

includes/admin/core/class-admin-forms.php
- This allows the info_text field to display a button element. Button element is used for Stripe's Connect/Disconnect functionality. The issue with anchor tag is, it requires to deattach the onclick function before you can disable it. With button, you only need to add an attribute 'disabled' to prevent the js function from triggering
=> Support button element for info_text field type in settings

includes/admin/assets/js/um-admin-modal.js
Fixed a conflict between scripts `um-admin-modal.js` and `bootstrap.min.js `
Screenshot of the error:
=> Fix admin modal conflict

includes/ajax/class-secure.php
This fixes the validation to check the current wp core version. It was set for theme updates.
=> Fix wp core current version in secure settings page

includes/admin/core/class-admin-settings.php
When a user that has subscribe role and has access to wp-admin, you can push 100GB of data to the install info. This additional nonce and user capability validation secures the install info.
=> Add nonce validation for download install info

includes/core/um-actions-profile.php
Fixed REST API endpoint [List Pages](https://developer.wordpress.org/rest-api/reference/pages/#list-pages).
Function `um_pre_profile_shortcode` disabled for the REST API requests.
=> REST API endpoint List Pages redirecting to the homepage

includes/core/um-actions-register.php
Do not redirect from the default WordPress registration page to the UM registration page if the page is not published.
=> Redirection from default registration to UM registration

includes/admin/core/class-admin-metabox.php
Without flushing UM()->metabox()->edit_mode_value variable it is possible to create fields with a wrong field icon and conditional logic values.
Ref screenshot:
=> Builder image class

includes/core/class-user.php
With the new permalink base `hash` function, it appears the hash keeps regenerating on each profile update. Is this intentional? I checked Upwork, and it doesn't regenerate the profile URL as it is a bad user experience and SEO.
While also debugging the hash issue, I've also observed that we have duplicate `generate_profile_slug` function calls on each update:
https://github.com/ultimatemember/ultimatemember/blob/master/includes/core/class-user.php#L922
https://github.com/ultimatemember/ultimatemember/blob/master/includes/core/um-actions-save-profile.php#L104
=> Avoid regenerating hash for profile URL on profile update

includes/admin/class-site-health.php
- fix implode empty value
PHP Fatal error: Uncaught TypeError: implode(): Argument ($array) must be of type ?array, string given in wp-content/plugins/ultimate-member/includes/admin/class-site-health.php:911
=> Fix site health

includes/core/class-roles-capabilities.php
- fix an error in PHP 8:
`Deprecated: stripslashes(): Passing null to parameter #1 ($string) of type string is deprecated in /xxxx/wp-content/plugins/ultimate-member/includes/core/class-roles-capabilities.php on line 677`
=> Fix stripslashes

includes/core/um-actions-form.php, includes/core/um-filters-fields.php, includes/um-short-functions.php
The YouTube Video field will support YouTube links with subdomain, like _m.youtube.com_ or _music.youtube.com_.
The YouTube Video field will support YouTube links with additional parameters `list`, `index`, `pp`, etc.
=> YouTube Video field does not support all YouTube links

assets/css/um-styles.css
- The icon for the password field is not showing after enabling the option "Show/hide password button" (Settings - General -Users).
=> Field icon visibility

includes/core/um-actions-login.php
- fix PHP 8 trim() error if the login form use the user_email field (issue #1360)
Deprecated: trim(): Passing null to parameter #1 ($string) of type string is deprecated in .../wp-includes/class-wp-user.php on line 211
=> Fix login error with user_email

includes/admin/class-secure.php, includes/ajax/class-secure.php, includes/common/class-secure.php
There's an issue with the security scanner. It doesn't filter all suspicious accounts and timestamps are incorrectly saved that caused invalid datetime differences.
=> Fix date and time to filter suspicious accounts + minor fixes to the timestamp in GMT

includes/core/um-filters-navmenu.php
Fixed the visibility of sub-items of hidden menu items.
Issue reported in the thread [Menu broken with 2.8.0 update](https://wordpress.org/support/topic/menu-broken-with-2-8-0-update/)
=> Menu broken with 2.8.0 update (CU-86cu48dm7)

includes/core/class-setup.php
When you register a predefined page in the extension,  it throws an error notice on "Create Pages":
```
[15-Dec-2023 15:35:11 UTC] PHP Warning:  Undefined array key "payment-successful" in /var/www/html/wp-content/plugins/ultimate-member/includes/core/class-setup.php on line 210
[15-Dec-2023 15:35:11 UTC] PHP Warning:  Undefined array key "payment-cancelled" in /var/www/html/wp-content/plugins/ultimate-member/includes/core/class-setup.php on line 210
[15-Dec-2023 15:35:11 UTC] PHP Warning:  Undefined array key "already-subscribed" in /var/www/html/wp-content/plugins/ultimate-member/includes/core/class-setup.php on line 210
[15-Dec-2023 15:35:11 UTC] PHP Warning:  Undefined array key "stripe" in /var/www/html/wp-content/plugins/ultimate-member/includes/core/class-setup.php on line 210
``` …
=> Fix error notice when generating predefined pages via extensions

includes/core/class-shortcodes.php
The `um` class has been removed from the body classes to fix page styling.
=> Body styles (CU-86cu8khqt)

includes/core/class-shortcodes.php
Added shortcode **[um_profile_link]** that displays a profile link.
Shortcode attributes:
- **class** - A link class.
- **title** - A link text.
- **user_id** - User ID. Post author if empty.
Example 1: `[um_profile_link]`
Example 2: `[um_profile_link title="Go to profile" user_id="29"]`
=> Shortcode to display profile link.

includes/core/class-mail.php, includes/core/class-password.php
Different email placeholders can use reset_url() and we have to use 1 time generated to avoid invalid keys.
The reset URL hash has been generated twice and we have the wrong hash in the reset password email.
=> Fixed reset url hash

includes/admin/class-secure.php, includes/admin/core/class-admin-users.php, includes/ajax/class-secure.php, includes/core/class-external-integrations.php, includes/core/class-fields.php, includes/core/um-actions-account.php, includes/core/um-filters-commenting.php, includes/core/um-filters-fields.php, includes/um-short-functions.php
=> CVE 2024 2765

includes/core/class-builtin.php
Fixed displaying Telegram and Discord social links in profile header.
Example:
=> Telegram and Discord social links in profile header

includes/core/class-form.php, includes/core/um-filters-fields.php
Issue: #1515 UM links to empty phone numbers
Empty field is displaying due to missing conditions. This condition fixes it;
```php
if ( empty( trim( str_replace( '+', '', $value ) ) ) ) {
return '';
}
```
- str_replace( '+', '', $value ): Removes all + characters from $value.
- trim( ... ): Trims whitespace from the resulting string.
- empty( ... ): Checks if the resulting string is empty.
Also tel field was added and sanitized upon updating profile to other similar fields
```php
case 'tel':
```
=> Fixed: UM links to empty phone numbers

includes/action-scheduler/class-init.php, includes/common/actions/class-emails.php, includes/common/class-users.php, includes/core/class-permalinks.php, includes/core/class-user.php, includes/core/um-actions-account.php, includes/core/um-actions-register.php
* Sending email notifications directly (without Action Scheduler) on user delete action;
* Changed activation handler priority for integration with Action Scheduler
* Added 'fetch_user_id' argument for fetching the necessary user before email sending when Action Scheduler is active.
=> Fixes 'um_dispatch_email' action #1589

includes/core/class-account.php, includes/core/class-form.php, includes/core/class-password.php
Password sanitize has been changed to the standard WordPress one - no `wp_unslash`, only `trim`.
=> Password set in Dashboard can't be used for UM login or vice versa (CU-86cxwy7ww)

changelog.txt, readme.txt
Corrected the release date for version 2.10.0 from February 17, 2025, to February 18, 2025, in both the changelog and readme files. No functional changes were made to the plugin.
=> Update plugin release date in changelog and readme files

includes/core/um-actions-profile.php
Fixed the warning that appears when using Gravatar.
```
Warning:getimagesize(/wordpress/avatar/e5ebe012578d467a89f3928ea7502bdc): Failed to open stream: No such file or directory in /www/wp-content/plugins/ultimate-member/includes/core/um-actions-profile.php on line 741
```
=> Gravatar warning

includes/core/class-account.php
- fixed change email permissions (issue #1679)
@nikitasinelnikov could you check?
I'm not sure if this change is needed. But on the other hand, the user who has a role that allows editing other members' accounts can't visit their account pages and "! um_user( 'can_edit_everyone' )" is an extra check.
=> Change email permissions

includes/class-init.php
Made the `deactivation` method public and added calls to unschedule specific actions related to email dispatch and account status checks. This ensures proper cleanup of scheduled tasks during plugin deactivation.
=> Refactor deactivation logic to unschedule additional actions

includes/core/class-builtin.php
- fixed Makedonia country name (https://wordpress.org/support/topic/trouble-with-flag-of-north-macedonia/#post-18517366). The new country name since 2019
=> Makedonia country name

includes/common/class-screen.php
Prevent caching on mobile devices for login, register, and account pages in Ultimate Member. This ensures updated content is always displayed and avoids caching-related issues on these critical pages.
=> Add mobile cache bypass for specific Ultimate Member pages

includes/admin/class-users-columns.php, includes/admin/core/class-admin-builder.php, includes/ajax/class-profile.php, includes/common/class-users.php, includes/core/class-roles-capabilities.php, includes/core/class-user.php, includes/core/um-actions-profile.php, includes/frontend/class-layouts.php, includes/um-deprecated-hooks.php, includes/um-short-functions.php
Replaced `um_can_view_profile` with `can_view_user` for consistent and robust access control across the plugin. Added additional checks for user existence and account status to improve security and accuracy when determining profile visibility. These changes ensure a more centralized and maintainable way to handle user permissions and profile access.
=> Refactor profile view logic to centralize user access checks
